spring.datasource.url=jdbc:h2:mem:ticketreservationtestdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/h2

spring.h2.console.enabled=false

logging.level.com.example.ticketreservation=INFO
logging.level.org.springframework.web=INFO
